witryna_do_przeprowadzania_testow/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/about', function () {
    return view('about');
});

Route::group(['middleware' => 'auth'], function() {

    Route::post('/courses/apply', 'CoursesController@register')->name('courses.register');
    Route::post('/courses/{course}', 'CoursesController@confirm')->name('courses.confirm');
    Route::get('/courses/apply', 'CoursesController@apply')->name('courses.apply');
    //Route::post('/courses/{course}/tests/{test}/questions/create', 'Courses\Tests\QuestionsController@create')->name('courses.tests.questions.create');

    Route::get('/courses/{course}/tests/{test}/show', 'Courses\Tests\ReportsController@download')->name('courses.tests.reports.download');
    Route::post('/courses/{course}/tests/{test}/show', 'Courses\TestsController@checkOpenQuestion')
        ->name('courses.tests.checkOpenQuestion');
    Route::get('/courses/{course}/tests/{test}/solve/{next}', 'Courses\TestsController@solve')->name('courses.tests.solve');
    Route::post('/courses/{course}/tests/{test}/check/{next}', 'Courses\TestsController@check')->name('courses.tests.check');

    Route::post('/courses/{course}/tests/{test}/questions/choose', 'Courses\Tests\QuestionsController@choose')->name('courses.tests.questions.choose');
    Route::post('/courses/{course}/tests/{test}/questions/getstore/{choice}', 'Courses\Tests\QuestionsController@getstore')->name('courses.tests.questions.getstore');

    Route::post('/courses/{course}/students/{student}', 'Courses\StudentController@show')->name('courses.students');

    Route::resource('/courses.tests.questions.answers','Courses\Tests\Questions\AnswersController');
    Route::resource('/courses.tests.questions', 'Courses\Tests\QuestionsController');
    Route::resource('/courses.students', 'Courses\StudentController');
    Route::resource('/courses.tests', 'Courses\TestsController');
    Route::resource('/courses', 'CoursesController');

});

witryna_do_przeprowadzania_testow/app/Http/Controllers/Courses/StudentController.php
<?php

namespace App\Http\Controllers\Courses;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Course;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('courses.students.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Course $course, $id)
    {
        return view('courses.students.show')->withCourse($course)
            ->with('id', $id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

witryna_do_przeprowadzania_testow/app/Http/Controllers/Courses/Tests/Questions/AnswersController.php
<?php

namespace App\Http\Controllers\Courses\Tests\Questions;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\All_answer;
use App\Correct_answer;
use App\Question;
use App\Course;
use App\Test;
use Validator;
use Illuminate\Support\Facades\DB;
use App\Categorization_answer;

class AnswersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Course $course, Test $test, Question $question)
    {
        return view('courses.tests.questions.answers.index')->withCourse($course)->withTest($test)->withQuestion($question);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Course $course, Test $test, Question $question)
    {
        return view('courses.tests.questions.answers.create')->withCourse($course)->withTest($test)->withQuestion($question);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request,Course $course,Test $test,Question $question)
    {


        switch($question->question_type)
        {
            case('single-answer'):
                $validator = Validator::make($request->all(), [
                    'answer' => 'required|max:255',
                ]);

                if ($validator->fails()) {
                    //return redirect()->route('courses.tests.questions.answer.create',[$course,$test,$question])
                    //    ->withErrors($validator)->withInput();
                    return view('courses.tests.questions.answers.create')->withCourse($course)->withTest($test)->withQuestion($question)->withErrors($validator);
                }
                if($request->correct){ //zabezpieczenie przed 2 poprawnymi odpowiedziami
                    if($question->correct_answers_count>0)
                    {
                        $validator->errors()
                            ->add('single', 'Only one correct answer in single-answer');
                        return view('courses.tests.questions.answers.create')->withCourse($course)->withTest($test)->withQuestion($question)->withErrors($validator);
                    }
            }
                $answer = new All_answer();
                $answer->answer = $request->answer;
                $question->all_answers()->save($answer);
                $answer->id = DB::table('all_answers')->max('id');
                $question->answers_count++;
                $test->questions()->save($question);
                if($request->correct) {
                    $answer->questions()->attach($question->id);
                    $question->correct_answers_count++;
                }
                $test->questions()->save($question);
                return view('courses.tests.questions.edit')->withCourse($course)->withTest($test)->withQuestion($question);

                break;
            case('multiple-answer'):
                $validator = Validator::make($request->all(), [
                    'answer' => 'required|max:255',
                ]);

                if ($validator->fails()) {
                    //return redirect()->route('courses.tests.questions.answer.create',[$course,$test,$question])
                    //    ->withErrors($validator)->withInput();
                    return view('courses.tests.questions.answers.create')->withCourse($course)->withTest($test)->withQuestion($question)->withErrors($validator);
                }
                $answer = new All_answer();
                $answer->answer = $request->answer;
                $question->all_answers()->save($answer);
                $answer->id = DB::table('all_answers')->max('id');
                $question->answers_count++;
                $test->questions()->save($question);
                if($request->correct) {
                    $answer->questions()->attach($question->id);
                    $question->correct_answers_count++;
                }
                $test->questions()->save($question);
                return view('courses.tests.questions.edit')->withCourse($course)->withTest($test)->withQuestion($question);

                break;
            case('open'):
                break;
            case('categorization'):
                $validator = Validator::make($request->all(), [
                    'first' => 'required|max:255',
                    'second' =>'required|max:255'
                ]);

                if ($validator->fails()) {
                    //return redirect()->route('courses.tests.questions.answer.create',[$course,$test,$question])
                    //    ->withErrors($validator)->withInput();
                    return view('courses.tests.questions.answers.create')->withCourse($course)->withTest($test)->withQuestion($question)->withErrors($validator);
                }
                $answer=new Categorization_answer();
                $answer->first=$request->first;
                $answer->second=$request->second;
                $question->categorization_answers()->save($answer);
                $answer->id=DB::table('categorization_answers')->max('id');
                $question->answers_count++;
                $test->questions()->save($question);

                return view('courses.tests.questions.edit')->withCourse($course)->withTest($test)->withQuestion($question);

                break;
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Course $course, Test $test, Question $question, $answerid)
    {
        return view('courses.tests.questions.answers.edit')
            ->withCourse($course)->withTest($test)->withQuestion($question)->with('answerid',$answerid);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Course $course, Test $test, Question $question, $answerid)
    {
        switch($question->question_type)
        {
            case('single-answer'):
            case('multiple-answer'):
                DB::table('all_answers')->where('id',$answerid)->update(['answer' => $request->answer]);
                break;
            case('categorization'):
                DB::table('categorization_answers')->where('id',$answerid)->update(['first' => $request->first , 'second' => $request->second]);
                break;
        }
        return view('courses.tests.questions.edit')->withCourse($course)->withTest($test)->withQuestion($question);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Course $course, Test $test, Question $question, $answerid)
    {
        switch($question->question_type)
        {
            case('single-answer'):
            case('multiple-answer'):

                if($question->answers()->where('answer_id', $answerid)->exists())
                    $question->correct_answers_count--;
                $question->answers_count--;

                DB::table('questions')->where('id',$question->id)
                    ->update(['answers_count' => $question->answers_count, 'correct_answers_count' => $question->correct_answers_count]);
                DB::table('all_answers')->where('id',$answerid)->delete();


            break;
            case('categorization'):
                $question->answers_count--;
                DB::table('questions')->where('id',$question->id)
                    ->update(['answers_count' => $question->answers_count]);

                DB::table('categorization_answers')->where('id',$answerid)->delete();
                break;
        }
        return view('courses.tests.questions.edit')->withCourse($course)->withTest($test)->withQuestion($question);

    }
}

witryna_do_przeprowadzania_testow/app/Http/Controllers/Courses/Tests/QuestionsController.php
<?php

namespace App\Http\Controllers\Courses\Tests;
use Illuminate\Support\Facades\DB;
use App\All_answer;
use App\Correct_answer;
use App\Question_stat;
use App\Question;
use App\Course;
use App\Test;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Validator;

class QuestionsController extends Controller
{

    public function index(Course $course,Test $test)
    {
        return view('courses.tests.questions.index')->withCourse($course)->withTest($test);
    }

    public function choose(Request $request, Course $course, Test $test){

        //if($request->method()=='post')

            return view('courses.tests.questions.create')->withCourse($course)->withTest($test)->with('choice',$request->question_type);
        //else return view('courses.tests.questions.create')->withCourse($course)->withTest($test)->with('choice',$request->question_type);
    }

    public function create(Course $course,Test $test)
    {
        return view('courses.tests.questions.create')->withCourse($course)->withTest($test);//->with('question_type',$request->input('question_type'));
    }


    public function getstore(Request $request, Course $course, Test $test, $choice){
//        $this->validate($request, [
//            'question' => 'required|max:255',
//        ]);
        $validator = Validator::make($request->all(), [
            'question' => 'required|max:255',
        ]);

        if ($validator->fails()) {
            return redirect()->route('courses.tests.questions.index',[$course,$test])
                ->withErrors($validator)->withInput();
        }

        switch($choice){
            case 'single-answer':
                $type=1;
                break;
            case 'multiple-answer':
                $type=2;
                break;
            case 'open':
                $type=3;
                break;
            case 'categorization':
                $type=4;
        }


        $question=new Question();
        $question->content=$request->question;
        $question->question_type=$type;
        $question->correct_answers_count=0;
        $question->answers_count=0;
        $test->questions()->save($question);
        $question->id= DB::table('questions')->max('id');

        $question_stat = new Question_stat();
        $question_stat->correct = 0;
        $question_stat->incorrect = 0;
        $question->question_stats()->save($question_stat);
        
        if($type==3)
            return redirect()->route('courses.tests.edit',[$course,$test]);

        //return view('courses.tests.questions.answers.create')->withCourse($course)->withTest($test)->withQuestion($question);
        return redirect()->route('courses.tests.questions.edit',[$course,$test,$question]);
    }

    public function store(Request $request, Course $course, Test $test)
    {

        $this->validate($request, [
            'question' => 'required|max:255',
        ]);

        $question=new Question();
        $question->content=$request->question;
        $question->question_type=1;
        $test->questions()->save($question);
        $question->id= DB::table('questions')->max('id');

        return view('courses.tests.questions.answers.index')->withCourse($course)->withTest($test)->withQuestion($question);
        //return redirect()->route('courses.tests.edit', [$course, $test]);
    }

    public function show(Question $question)
    {
        //
    }

    public function edit(Course $course, Test $test, Question $question)
    {
        return view('courses.tests.questions.edit')->withCourse($course)->withTest($test)->withQuestion($question);
    }

    public function update(Request $request, Course $course, Test $test, Question $question)
    {
        DB::table('questions')->where('id',$question->id)->update(['content' => $request->question]);
        return view('courses.tests.edit')->withCourse($course)->withTest($test);

    }

    public function destroy(Course $course, Test $test, Question $question)
    {
        switch($question->question_type)
        {
            case('single-answer'):
            case('multiple-answer'):
                DB::table('questions')->where('id',$question->id)->delete();

                //DB::table('all_answers')->where('id',$answerid)->delete();


                break;
            case('categorization'):

                DB::table('questions')->where('id',$question->id)
                    ->delete();

        }
        return view('courses.tests.edit')->withCourse($course)->withTest($test);

    }
}

witryna_do_przeprowadzania_testow/app/Http/Controllers/Courses/Tests/ReportsController.php
<?php

namespace App\Http\Controllers\Courses\Tests;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use PDF;
use App\Course;
use App\Test;

class ReportsController extends Controller
{
    public function download(Course $course, Test $test)
    {
        $data = ['course' => $course, 'test' => $test];

        $pdf = PDF::loadView('courses.tests.reports.report', $data);
        return $pdf->download('raport.pdf');
    }
}

witryna_do_przeprowadzania_testow/resources/views/courses/apply.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="bg-primary text-white">
                        <div class="panel-heading">Apply</div>
                    </div>
                    <div class="panel-body">
                        Page to apply for the course
                        <form class="form-horizontal" method="post" action="{{ route('courses.register') }}">
                            {{ csrf_field() }}
                            <br>
                                <select class="form-control" name="course">
                                    @foreach($courses as $course)
                                        <option value="{{$course->id}}">{{$course->id}} {{$course->name}} {{$course->user->email}}</option>
                                    @endforeach
                                </select>
                            <br>
                            <button type="submit" class="btn btn-primary">Apply</button>


                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

witryna_do_przeprowadzania_testow/resources/views/courses/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="bg-primary text-white">
                        <div class="panel-heading">Courses</div>
                    </div>
                    <div class="panel-body">

                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        <form class="form-horizontal" method="post" action="{{ route('courses.store') }}">
                            {{ csrf_field() }}

                            <div class="form-group">
                                <label for="name" class="col-md-4 control-label">Name:</label>
                                <div class="col-md-6">
                                    <input id="name" class="form-control" type="text" name="name">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="description" class="col-md-4 control-label">Description:</label>
                                <div class="col-md-6">
                                    <input id="description" type="text" class="form-control" name="description">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Create
                                    </button>
                                </div>
                            </div>
                        </form>
                        <a href="{{route('courses.index')}}">Back to course list...</a>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

witryna_do_przeprowadzania_testow/resources/views/courses/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="bg-primary text-white">
                        <div class="panel-heading">Courses</div>
                    </div>

                    <div class="panel-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif



                        @foreach(Auth::user()->courses as $course)
                            <div  class="list-group">
                                <a href="{{ route('courses.show', $course->id) }}" class="list-group-item list-group-item-action flex-column align-items-start">

                                    <div class="d-flex w-100 justify-content-between">
                                        <h5 class="mb-1"><b>{{ $course['name'] }}</b></h5>
                                    </div>
                                    <p  class="text-primary text-nowrap">{{$course['description']}}</p>
                                </a>
                            </div>
                        @endforeach
                        @if (Auth::user()->identity == "teacher")
                            <a href="{{ route('courses.create') }}" class="btn btn-primary pull-right" role="button">
                                Create new...
                            </a>
                        @endif

                        @if (Auth::user()->identity == "student")
                            <a href="{{ route('courses.apply') }}" class="btn btn-primary" role="button">
                                Apply for...
                            </a>
                        @endif

                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection

witryna_do_przeprowadzania_testow/resources/views/courses/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="bg-primary text-white">
                        <div class="panel-heading">Details</div>
                    </div>
                    <div class="panel-body">
                        <strong>{{ $course->name }}</strong> <br>
                        <strong>Teacher: </strong>{{ $course->user->email }} <br>
                        <strong>Description: </strong>{{ $course->description }} <br>

                        @if (Auth::user()->identity == "teacher")
                            <br> <h5><b>Students:</b> </h5>
                            <ul class="list-group">
                                @foreach($course->users as $student)
                                    @if($student->pivot->confirmed == true)
                                        <a href="{{route('courses.students', [$course, $student])}}" class="list-group-item list-group-item-action flex-column align-items-start">
                                                <b>{{ $student->name }}</b>
                                        </a>
                                    @endif
                                @endforeach
                            </ul>
                            <h5><b>Not confirmed students: </b></h5>

                                @foreach($course->users as $student)
                                    @if($student->pivot->confirmed == false)

                                        <form  class="form-inline" method="post" action="{{ route('courses.confirm', $course) }}">
                                            {{ csrf_field() }}
                                            <input type="hidden" value="{{$student->id}}" name="user_id">

                                            <label class="mr-sm-2 text-primary" for="confirmation">{{ $student->name }}</label>
                                            <select id="confirmation" class="form-control" name="confirmation">
                                                <option value="true">Confirm</option>
                                                <option value="false">Reject</option>
                                            </select>
                                            <button type="submit" class="btn btn-primary align-right">
                                                Press
                                            </button>

                                        </form>
                                    @endif
                                @endforeach

                            <a href="{{ route('courses.tests.index', $course) }}" class="btn btn-primary pull-right" >Manage tests</a>
                        @endif

                        @if (Auth::user()->identity == "student")
                            @if(Auth::user()->courses->where('id', $course->id)->first()->pivot->confirmed  == false)
                                You are not confirmed
                            @else
                                <strong>Available tests: </strong><br>
                                @foreach($course->tests as $test)

                                    <?php
                                    $today = new DateTime("now",new DateTimeZone('Europe/Warsaw'));

                                    $deadline = new DateTime($test['deadline'],new DateTimeZone('Europe/Warsaw'));
                                    $release = new DateTime($test['release_date'],new DateTimeZone('Europe/Warsaw'));
                                    ?>

                                    @if ($deadline > $today and $release < new $today)
                                    <li>
                                        <strong>{{ $test['name'] }}</strong>
                                        @if(DB::table('user_points')->where('user_id', Auth::id())->where('test_id', $test->id)->value('finished') == true)
                                            Points: {{DB::table('user_points')->where('user_id', Auth::id())->where('test_id', $test->id)->value('points')}}
                                            / {{$test->questions()->count()}}
                                        @else
                                            <a href="{{ route('courses.tests.show', [$course,$test]) }}">Solve</a>
                                        @endif
                                    </li>
                                    @endif

                                @endforeach
                            @endif
                        @endif

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection